-- MySQL Script generated by MySQL Workbench
-- Wed Jan 18 19:05:04 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema meta
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `metadb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `metadb` DEFAULT CHARACTER SET utf8 ;
USE `metadb` ;

-- -----------------------------------------------------
-- Table `metadb`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `metadb`.`user` ;

CREATE TABLE IF NOT EXISTS `metadb`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `metadb`.`posts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `metadb`.`posts` ;

CREATE TABLE IF NOT EXISTS `metadb`.`posts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `post` VARCHAR(255) NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`, `user_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_posts_user_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_posts_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `metadb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

insert into `user` (`name`,`password`)
values("um","123456");
insert into `user` (`name`,`password`)
values("dois","123456");
insert into `user` (`name`,`password`)
values("tres","123456");

insert into `posts` (`post`, `user_id`)
values("fdhfgjhyf", "1");
insert into `posts` (`post`, `user_id`)
values("Ariosvaldo AAAAAA", "2");
insert into `posts` (`post`, `user_id`)
values("Jubscreidilson", "3");


select * from posts;
select * from metadb.User;
 




SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
